# MoBoxFrp 节点配置文件
# By MossCG

# 主控地址（结尾不要有多余斜杠）
address: "http://127.0.0.1:2026"

# 节点编号及密码
nodeID: "sz1"
nodeAuth: "123"

#系统类型
#Windows or Linux
systemType: "Windows"


#----------------------------------
#是否显示调试信息
debug: false